# Generated by Django 5.1.3 on 2024-12-01 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.CharField(max_length=50, unique=True)),
                ('trade_name', models.TextField()),
                ('international_name', models.TextField()),
                ('form', models.TextField()),
                ('conditions', models.TextField()),
                ('composition', models.TextField()),
                ('pharmacotherapeutic_group', models.TextField()),
                ('atc_code', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShelfLife',
            fields=[
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='djangoProject.drug')),
                ('bio_origin', models.BooleanField(default=False)),
                ('plant_origin', models.BooleanField(default=False)),
                ('orphan_drug', models.BooleanField(default=False)),
                ('homeopathic', models.BooleanField(default=False)),
                ('mnn_type', models.BooleanField(default=False)),
                ('manual_url', models.TextField(blank=True, null=True)),
                ('shelf_life', models.TextField(blank=True, null=True)),
                ('shelf_life_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shelf_life_unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.drugtype'),
        ),
        migrations.CreateModel(
            name='DrugManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.drug')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.manufacturer')),
            ],
            options={
                'unique_together': {('drug', 'manufacturer')},
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturers',
            field=models.ManyToManyField(through='djangoProject.DrugManufacturer', to='djangoProject.manufacturer'),
        ),
    ]
